'use client';

import { createContext, use } from 'react';

export interface FormProps {
  required?: boolean;
  error?: boolean;
  disabled?: boolean;
  color?: 'dark' | 'light';
  /** Id of the associated HelperText, generated by Control via `useId`. */
  helperTextId?: string;
}

const FormContext = createContext<FormProps>({
  required: false,
  error: false,
  disabled: false,
  color: 'dark',
});

export function FormProvider({
  children,
  ...formProps
}: React.PropsWithChildren<FormProps>) {
  return <FormContext value={formProps}>{children}</FormContext>;
}

export function useFormContext(formProps?: FormProps) {
  const formContext = use(FormContext);

  return {
    ...formContext,
    ...formProps,
  };
}

/** Combines a consumer-provided `aria-describedby` with the HelperText id. */
export function resolveAriaDescribedBy(
  explicitAriaDescribedBy: string | undefined,
  helperTextId: string | undefined
): string | undefined {
  return (
    [explicitAriaDescribedBy, helperTextId].filter(Boolean).join(' ') ||
    undefined
  );
}
