'use client';

import { createContext, use } from 'react';

export interface FormProps {
  required?: boolean;
  error?: boolean;
  disabled?: boolean;
  color?: 'dark' | 'light';
  /** Id of the associated HelperText, generated by Control via `useId`. */
  helperTextId?: string;
}

interface FormContextValue extends FormProps {
  /** Lets a HelperText with an explicit `id` keep the control pointing at it. */
  registerHelperTextId?: (helperTextId: string | undefined) => void;
}

const FormContext = createContext<FormContextValue>({
  required: false,
  error: false,
  disabled: false,
  color: 'dark',
});

export function FormProvider({
  children,
  ...formProps
}: React.PropsWithChildren<FormContextValue>) {
  return <FormContext value={formProps}>{children}</FormContext>;
}

export function useFormContext(formProps?: FormProps): FormProps {
  const { registerHelperTextId: _registerHelperTextId, ...formContext } =
    use(FormContext);

  return {
    ...formContext,
    ...formProps,
  };
}

export function useRegisterHelperTextId() {
  return use(FormContext).registerHelperTextId;
}

/** Keeps a consumer-provided `aria-invalid` over the `error`-derived one. */
export function resolveAriaInvalid(
  explicitAriaInvalid: React.AriaAttributes['aria-invalid'],
  error: boolean | undefined
): React.AriaAttributes['aria-invalid'] {
  return explicitAriaInvalid ?? (error ? true : undefined);
}

/** Combines a consumer-provided `aria-describedby` with the HelperText id. */
export function resolveAriaDescribedBy(
  explicitAriaDescribedBy: string | undefined,
  helperTextId: string | undefined
): string | undefined {
  return (
    [explicitAriaDescribedBy, helperTextId].filter(Boolean).join(' ') ||
    undefined
  );
}
