/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [],
  theme: {
    extend: {
      fontFamily: {
        original: [
          'Menlo',
          'ui-monospace',
          'SFMono-Regular',
          'Monaco',
          'Consolas',
          'Liberation Mono',
          'Courier New',
          'var(--font-noto-sans-jp)',
          'monospace',
        ],
      },
      fontSize: {
        advert: 'var(--advert)',
        'slogan-lg': 'var(--slogan-lg)',
        'slogan-sm': 'var(--slogan-sm)',
        'header-lg': 'var(--header-lg)',
        'header-sm': 'var(--header-sm)',
        'heading-1': 'var(--heading-1)',
        'heading-2': 'var(--heading-2)',
        'heading-3': 'var(--heading-3)',
        'heading-4': 'var(--heading-4)',
        'heading-5': 'var(--heading-5)',
        'heading-6': 'var(--heading-6)',
        'body-lg': 'var(--body-lg)',
        'body-md': 'var(--body-md)',
        'body-sm': 'var(--body-sm)',
        caption: 'var(--caption)',
        'button-lg': 'var(--button-lg)',
        'button-md': 'var(--button-md)',
        'button-sm': 'var(--button-sm)',
      },
      textColor: {
        'color-base': 'rgb(var(--color-base-8) / <alpha-value>)',
      },
      lineHeight: {
        advert: 'calc(var(--advert)*var(--leading-rate))',
        'slogan-lg': 'calc(var(--slogan-lg)*var(--leading-rate))',
        'slogan-sm': 'calc(var(--slogan-sm)*var(--leading-rate))',
        'header-lg': 'calc(var(--header-lg)*var(--leading-rate))',
        'header-sm': 'calc(var(--header-sm)*var(--leading-rate))',
        'heading-1': 'calc(var(--heading-1)*var(--leading-rate))',
        'heading-2': 'calc(var(--heading-2)*var(--leading-rate))',
        'heading-3': 'calc(var(--heading-3)*var(--leading-rate))',
        'heading-4': 'calc(var(--heading-4)*var(--leading-rate))',
        'heading-5': 'calc(var(--heading-5)*var(--leading-rate))',
        'heading-6': 'calc(var(--heading-6)*var(--leading-rate))',
        'body-lg': 'calc(var(--body-lg)*var(--leading-rate))',
        'body-md': 'calc(var(--body-md)*var(--leading-rate))',
        'body-sm': 'calc(var(--body-sm)*var(--leading-rate))',
        caption: 'calc(var(--caption)*var(--leading-rate))',
        'button-lg': 'calc(var(--button-lg)*var(--leading-rate))',
        'button-md': 'calc(var(--button-md)*var(--leading-rate))',
        'button-sm': 'calc(var(--button-sm)*var(--leading-rate))',
      },
      colors: {
        main: 'rgb(var(--color-main) / <alpha-value>)',
        'main-light': 'rgb(var(--color-main-light) / <alpha-value>)',
        'main-dark': 'rgb(var(--color-main-dark) / <alpha-value>)',
        accent: 'rgb(var(--color-accent) / <alpha-value>)',
        'accent-light': 'rgb(var(--color-accent-light) / <alpha-value>)',
        'accent-dark': 'rgb(var(--color-accent-dark) / <alpha-value>)',
      },
      animation: {
        slide: 'slide 0.8s ease-in 1',
      },
      keyframes: {
        slide: {
          from: {
            transform: 'translate(-8rem, -50%)',
            opacity: 0,
          },
          to: {
            transform: 'translate(0, -50%)',
            opacity: 1,
          },
        },
      },
    },
  },
  plugins: [],
};
