/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [],
  theme: {
    extend: {
      fontFamily: {
        original: [
          'Menlo',
          'ui-monospace',
          'SFMono-Regular',
          'Monaco',
          'Consolas',
          'Liberation Mono',
          'Courier New',
          'var(--font-noto-sans-jp)',
          'monospace',
        ],
      },
      fontSize: {
        advert: 'var(--advert)',
        slogan: 'var(--slogan)',
        'big-header': 'var(--big-header)',
        'heading-1': 'var(--heading-1)',
        'heading-2': 'var(--heading-2)',
        'heading-3': 'var(--heading-3)',
        'heading-4': 'var(--heading-4)',
        'heading-5': 'var(--heading-5)',
        'heading-6': 'var(--heading-6)',
        'subtitle-lg': 'var(--subtitle-lg)',
        'subtitle-md': 'var(--subtitle-md)',
        'subtitle-sm': 'var(--subtitle-sm)',
        'body-lg': 'var(--body-lg)',
        'body-md': 'var(--body-md)',
        'body-sm': 'var(--body-sm)',
        caption: 'var(--caption)',
        'button-lg': 'var(--button-lg)',
        'button-md': 'var(--button-md)',
        'button-sm': 'var(--button-sm)',
      },
      textColor: {
        'color-base': 'rgb(var(--color-base-black) / <alpha-value>)',
      },
      lineHeight: {
        advert: 'calc(var(--advert)*var(--leading-rate))',
        'slogan-lg': 'calc(var(--slogan-lg)*var(--leading-rate))',
        'slogan-sm': 'calc(var(--slogan-sm)*var(--leading-rate))',
        'header-lg': 'calc(var(--header-lg)*var(--leading-rate))',
        'header-sm': 'calc(var(--header-sm)*var(--leading-rate))',
        'heading-1': 'calc(var(--heading-1)*var(--leading-rate))',
        'heading-2': 'calc(var(--heading-2)*var(--leading-rate))',
        'heading-3': 'calc(var(--heading-3)*var(--leading-rate))',
        'heading-4': 'calc(var(--heading-4)*var(--leading-rate))',
        'heading-5': 'calc(var(--heading-5)*var(--leading-rate))',
        'heading-6': 'calc(var(--heading-6)*var(--leading-rate))',
        'body-lg': 'calc(var(--body-lg)*var(--leading-rate))',
        'body-md': 'calc(var(--body-md)*var(--leading-rate))',
        'body-sm': 'calc(var(--body-sm)*var(--leading-rate))',
        caption: 'calc(var(--caption)*var(--leading-rate))',
        'button-lg': 'calc(var(--button-lg)*var(--leading-rate))',
        'button-md': 'calc(var(--button-md)*var(--leading-rate))',
        'button-sm': 'calc(var(--button-sm)*var(--leading-rate))',
      },
      colors: {
        main: 'rgb(var(--color-main) / <alpha-value>)',
        'main-light': 'rgb(var(--color-main-light) / <alpha-value>)',
        'main-dark': 'rgb(var(--color-main-dark) / <alpha-value>)',
        accent: 'rgb(var(--color-accent) / <alpha-value>)',
        'accent-light': 'rgb(var(--color-accent-light) / <alpha-value>)',
        'accent-dark': 'rgb(var(--color-accent-dark) / <alpha-value>)',
        base: 'rgb(var(--color-base) / <alpha-value>)',
        'base-light': 'rgb(var(--color-base-light) / <alpha-value>)',
        'base-dark': 'rgb(var(--color-base-dark) / <alpha-value>)',
        error: 'rgb(var(--color-error) / <alpha-value>)',
        'error-light': 'rgb(var(--color-error-light) / <alpha-value>)',
        'error-dark': 'rgb(var(--color-error-dark) / <alpha-value>)',
        warning: 'rgb(var(--color-warning) / <alpha-value>)',
        'warning-light': 'rgb(var(--color-warning-light) / <alpha-value>)',
        'warning-dark': 'rgb(var(--color-warning-dark) / <alpha-value>)',
        info: 'rgb(var(--color-info) / <alpha-value>)',
        'info-light': 'rgb(var(--color-info-light) / <alpha-value>)',
        'info-dark': 'rgb(var(--color-info-dark) / <alpha-value>)',
        success: 'rgb(var(--color-success) / <alpha-value>)',
        'success-light': 'rgb(var(--color-success-light) / <alpha-value>)',
        'success-dark': 'rgb(var(--color-success-dark) / <alpha-value>)',
        'color-base': 'rgb(var(--color-base-black) / <alpha-value>)',
      },
      animation: {
        slide: 'slide 0.8s ease-in 1',
        scrollHelp: 'scrollHelp 5s ease-in-out infinite both',
      },
      keyframes: {
        slide: {
          from: {
            transform: 'translate(-8rem, -50%)',
            opacity: 0,
          },
          to: {
            transform: 'translate(0, -50%)',
            opacity: 1,
          },
        },
        scrollHelp: {
          '0%, 100%': {
            transform: 'translateX(0)',
          },
          '10%, 30%, 50%, 70%': {
            transform: 'translateX(-10px)',
          },
          '20%, 40%, 60%': {
            transform: 'translateX(10px)',
          },
          '80%': {
            transform: 'translateX(8px)',
          },
          '90%': {
            transform: 'translateX(-8px)',
          },
        },
      },
    },
  },
  plugins: [],
};
