// Generates iconUrls.generated.ts: static SVG imports for the curated
// ICON_NAMES set, grouped into name->url maps. Static imports are
// bundler-agnostic (webpack asset modules and esbuild's dataurl loader both
// resolve them to a URL string), unlike require.context which is webpack-only
// and breaks any non-webpack bundler. Re-run `pnpm -F ui generate:icons`
// after editing const.ts.
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));

const namesOf = (key) => {
  const src = readFileSync(join(here, 'const.ts'), 'utf8');
  const block = src.match(new RegExp(`${key}\\s*=\\s*\\[([^\\]]*)\\]`));
  if (!block) throw new Error(`${key} not found in const.ts`);
  return [...block[1].matchAll(/'([^']+)'/g)].map((m) => m[1]);
};

const importName = (prefix, name) =>
  `${prefix}_${name.replace(/[^a-zA-Z0-9]/g, '_')}`;

const groups = [
  { map: 'multiColorIcons', dir: 'multi-color-icons', prefix: 'mc', names: namesOf('MULTI_COLOR_ICON_NAMES') },
  { map: 'heroOutlineIcons', dir: 'hero-icons/outline', prefix: 'ho', names: namesOf('HERO_ICON_NAMES') },
  { map: 'heroSolidIcons', dir: 'hero-icons/solid', prefix: 'hs', names: namesOf('HERO_ICON_NAMES') },
];

const imports = [];
const maps = [];
for (const { map, dir, prefix, names } of groups) {
  const entries = [];
  for (const name of names) {
    if (!existsSync(join(here, dir, `${name}.svg`))) {
      throw new Error(`missing icon: ${dir}/${name}.svg`);
    }
    const local = importName(prefix, name);
    imports.push(`import ${local} from './${dir}/${name}.svg';`);
    entries.push(`  '${name}': ${local},`);
  }
  maps.push(`export const ${map}: Record<string, IconUrl> = {\n${entries.join('\n')}\n};`);
}

// SVG imports resolve to a URL string (webpack asset modules, esbuild dataurl)
// or a static-image object ({ default: { src } }) depending on the bundler —
// mirror the original require.context handling by accepting both.
const typeDecl = 'export type IconUrl = string | { src: string } | { default: { src: string } };';
const out = `// AUTO-GENERATED by generateIconUrls.mjs — do not edit by hand.\n// Re-run \`pnpm -F ui generate:icons\` after changing const.ts.\n${imports.join('\n')}\n\n${typeDecl}\n\n${maps.join('\n\n')}\n`;
writeFileSync(join(here, 'iconUrls.generated.ts'), out);
console.log(`wrote iconUrls.generated.ts (${imports.length} imports)`);
