// AUTO-GENERATED by generateIconUrls.mjs — do not edit by hand.
// Re-run `node generateIconUrls.mjs` after changing const.ts.
import mc_typescript from './multi-color-icons/typescript.svg';
import mc_python from './multi-color-icons/python.svg';
import mc_golang from './multi-color-icons/golang.svg';
import mc_react from './multi-color-icons/react.svg';
import mc_figma from './multi-color-icons/figma.svg';
import mc_wordpress from './multi-color-icons/wordpress.svg';
import mc_jupyter from './multi-color-icons/jupyter.svg';
import mc_tensorflow from './multi-color-icons/tensorflow.svg';
import mc_aws from './multi-color-icons/aws.svg';
import mc_google_cloud from './multi-color-icons/google-cloud.svg';
import mc_docker from './multi-color-icons/docker.svg';
import mc_circleci from './multi-color-icons/circleci.svg';
import mc_github from './multi-color-icons/github.svg';
import mc_x from './multi-color-icons/x.svg';
import mc_instagram from './multi-color-icons/instagram.svg';
import mc_line from './multi-color-icons/line.svg';
import mc_facebook from './multi-color-icons/facebook.svg';
import mc_hatena from './multi-color-icons/hatena.svg';
import mc_pinterest from './multi-color-icons/pinterest.svg';
import ho_arrow_top_right_on_square from './hero-icons/outline/arrow-top-right-on-square.svg';
import ho_x_mark from './hero-icons/outline/x-mark.svg';
import ho_chevron_double_right from './hero-icons/outline/chevron-double-right.svg';
import ho_inbox_stack from './hero-icons/outline/inbox-stack.svg';
import ho_bars_3 from './hero-icons/outline/bars-3.svg';
import ho_chevron_left from './hero-icons/outline/chevron-left.svg';
import ho_chevron_right from './hero-icons/outline/chevron-right.svg';
import ho_magnifying_glass from './hero-icons/outline/magnifying-glass.svg';
import ho_photo from './hero-icons/outline/photo.svg';
import ho_user_circle from './hero-icons/outline/user-circle.svg';
import ho_user from './hero-icons/outline/user.svg';
import ho_information_circle from './hero-icons/outline/information-circle.svg';
import ho_check_circle from './hero-icons/outline/check-circle.svg';
import ho_exclamation_triangle from './hero-icons/outline/exclamation-triangle.svg';
import ho_x_circle from './hero-icons/outline/x-circle.svg';
import ho_arrow_left from './hero-icons/outline/arrow-left.svg';
import ho_arrow_right from './hero-icons/outline/arrow-right.svg';
import ho_chevron_up from './hero-icons/outline/chevron-up.svg';
import ho_list_bullet from './hero-icons/outline/list-bullet.svg';
import hs_arrow_top_right_on_square from './hero-icons/solid/arrow-top-right-on-square.svg';
import hs_x_mark from './hero-icons/solid/x-mark.svg';
import hs_chevron_double_right from './hero-icons/solid/chevron-double-right.svg';
import hs_inbox_stack from './hero-icons/solid/inbox-stack.svg';
import hs_bars_3 from './hero-icons/solid/bars-3.svg';
import hs_chevron_left from './hero-icons/solid/chevron-left.svg';
import hs_chevron_right from './hero-icons/solid/chevron-right.svg';
import hs_magnifying_glass from './hero-icons/solid/magnifying-glass.svg';
import hs_photo from './hero-icons/solid/photo.svg';
import hs_user_circle from './hero-icons/solid/user-circle.svg';
import hs_user from './hero-icons/solid/user.svg';
import hs_information_circle from './hero-icons/solid/information-circle.svg';
import hs_check_circle from './hero-icons/solid/check-circle.svg';
import hs_exclamation_triangle from './hero-icons/solid/exclamation-triangle.svg';
import hs_x_circle from './hero-icons/solid/x-circle.svg';
import hs_arrow_left from './hero-icons/solid/arrow-left.svg';
import hs_arrow_right from './hero-icons/solid/arrow-right.svg';
import hs_chevron_up from './hero-icons/solid/chevron-up.svg';
import hs_list_bullet from './hero-icons/solid/list-bullet.svg';

export type IconUrl = string | { src: string } | { default: { src: string } };

export const multiColorIcons: Record<string, IconUrl> = {
  'typescript': mc_typescript,
  'python': mc_python,
  'golang': mc_golang,
  'react': mc_react,
  'figma': mc_figma,
  'wordpress': mc_wordpress,
  'jupyter': mc_jupyter,
  'tensorflow': mc_tensorflow,
  'aws': mc_aws,
  'google-cloud': mc_google_cloud,
  'docker': mc_docker,
  'circleci': mc_circleci,
  'github': mc_github,
  'x': mc_x,
  'instagram': mc_instagram,
  'line': mc_line,
  'facebook': mc_facebook,
  'hatena': mc_hatena,
  'pinterest': mc_pinterest,
};

export const heroOutlineIcons: Record<string, IconUrl> = {
  'arrow-top-right-on-square': ho_arrow_top_right_on_square,
  'x-mark': ho_x_mark,
  'chevron-double-right': ho_chevron_double_right,
  'inbox-stack': ho_inbox_stack,
  'bars-3': ho_bars_3,
  'chevron-left': ho_chevron_left,
  'chevron-right': ho_chevron_right,
  'magnifying-glass': ho_magnifying_glass,
  'photo': ho_photo,
  'user-circle': ho_user_circle,
  'user': ho_user,
  'information-circle': ho_information_circle,
  'check-circle': ho_check_circle,
  'exclamation-triangle': ho_exclamation_triangle,
  'x-circle': ho_x_circle,
  'arrow-left': ho_arrow_left,
  'arrow-right': ho_arrow_right,
  'chevron-up': ho_chevron_up,
  'list-bullet': ho_list_bullet,
};

export const heroSolidIcons: Record<string, IconUrl> = {
  'arrow-top-right-on-square': hs_arrow_top_right_on_square,
  'x-mark': hs_x_mark,
  'chevron-double-right': hs_chevron_double_right,
  'inbox-stack': hs_inbox_stack,
  'bars-3': hs_bars_3,
  'chevron-left': hs_chevron_left,
  'chevron-right': hs_chevron_right,
  'magnifying-glass': hs_magnifying_glass,
  'photo': hs_photo,
  'user-circle': hs_user_circle,
  'user': hs_user,
  'information-circle': hs_information_circle,
  'check-circle': hs_check_circle,
  'exclamation-triangle': hs_exclamation_triangle,
  'x-circle': hs_x_circle,
  'arrow-left': hs_arrow_left,
  'arrow-right': hs_arrow_right,
  'chevron-up': hs_chevron_up,
  'list-bullet': hs_list_bullet,
};
